List commits in repo

diff --git a/.github/workflows/checkin.yml b/.github/workflows/checkin.yml
--- a/.github/workflows/checkin.yml
+++ b/.github/workflows/checkin.yml
@@ -5,21 +5,21 @@ jobs:
   check_pr:
     runs-on: ubuntu-latest
     steps:
-    - uses: actions/checkout@v1
+      - uses: actions/checkout@v1
 
-    - name: "npm ci"
-      run: npm ci
+      - name: "yarn install"
+        run: yarn install
 
-    - name: "npm run build"
-      run: npm run build
+      - name: "yarn run build"
+        run: yarn run build
 
-    - name: "npm run test"
-      run: npm run test
+      - name: "yarn run test"
+        run: yarn run test
 
-    - name: "check for uncommitted changes"
-      # Ensure no changes, but ignore node_modules dir since dev/fresh ci deps installed.
-      run: |
-        git diff --exit-code --stat -- . ':!node_modules' \
-        || (echo "##[error] found changed files after build. please 'npm run build && npm run format'" \
-                 "and check in all changes" \
-            && exit 1)
+      - name: "check for uncommitted changes"
+        # Ensure no changes, but ignore node_modules dir since dev/fresh ci deps installed.
+        run: |
+          git diff --exit-code --stat -- . ':!node_modules' \
+          || (echo "##[error] found changed files after build. please 'yarn run build && yarn run format'" \
+                   "and check in all changes" \
+              && exit 1)
